---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: klustered-us-live
  namespace: default
spec:
  secretName: klustered-us-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.klustered.us"
  dnsNames:
  - "klustered.us"
  - "*.klustered.us"
