apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  destination:
    namespace: default
    name: in-cluster
  project: development
  source:
    path: registry/projects/development/cluster/mgmt
    repoURL: https://github.com/StevenBuglione/home-lab
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true