---
- name: Install && Configure Rancher
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Install Rancher Repository
      ansible.builtin.shell: |
        helm repo add rancher-alpha https://releases.rancher.com/server-charts/alpha
        helm repo update
        helm fetch rancher-alpha/rancher

    - name: Check if cattle-system Namespace Exists
      ansible.builtin.shell: |
        kubectl get namespace cattle-system
      register: namespace_check
      ignore_errors: yes

    - name: Create Rancher Namespace
      ansible.builtin.shell: |
        kubectl create namespace cattle-system
      when: namespace_check is failed


    - name: Install Rancher
      ansible.builtin.shell: |
        helm install rancher rancher-alpha/rancher --devel \
        --namespace cattle-system \
        --set hostname=rancher.home.io \
        --set bootstrapPassword=admin
        kubectl -n cattle-system rollout status deploy/rancher
        kubectl -n cattle-system get deploy rancher

    - name: Configure Rancher
      ansible.builtin.shell: |
        kubectl expose deployment rancher --name=rancher-lb --port=443 --type=LoadBalancer -n cattle-system