---
- name: Install k3sup on local machine
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Check if k3sup is installed
      ansible.builtin.command:
        cmd: k3sup version
      register: k3sup_installed
      ignore_errors: yes

    - name: Install k3sup
      ansible.builtin.shell: |
        echo -e " \033[31;5mk3sup not found, installing\033[0m"
        curl -sLS https://get.k3sup.dev | sh
        sudo install k3sup /usr/local/bin/
      when: k3sup_installed.rc != 0

    - name: k3sup already installed
      ansible.builtin.debug:
        msg: " \033[32;5mk3sup already installed\033[0m"
      when: k3sup_installed.rc == 0
