---
- name: Install kube-vip as Network LoadBalancer
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Install the kube-vip Cloud Provider
      ansible.builtin.shell:
        cmd: kubectl apply -f https://raw.githubusercontent.com/kube-vip/kube-vip-cloud-provider/main/manifest/kube-vip-cloud-controller.yaml

    - name: Delete existing kube-vip ConfigMap if it exists
      ansible.builtin.shell:
        cmd: kubectl delete configmap kubevip -n kube-system
      ignore_errors: yes

    - name: Create ConfigMap for kube-vip IP range
      ansible.builtin.shell:
        cmd: kubectl create configmap -n kube-system kubevip --from-literal range-global={{ lbrange }}

