argo_cd_repo: "StevenBuglione/home-lab"
argo_cd_branch: "main"
argo_cd_project: "argo-cd/registry/projects/development/project-dev.yml"
argo_cd_root_app: "argo-cd/registry/projects/development/root-app-dev.yml"